config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  # root 'articles#index'
  root 'application#home'

  post '/user_lang/:user_lang', to: 'application#change_user_language'

  resources :champions, only: [:index, :show]
  resources :recommendations, except: [:index, :destroy]
end

app/models/champion.rb
class Champion < ApplicationRecord
  has_many :champion_translations, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :champion_translations

  has_many :statistics, dependent: :destroy

  validates :key, uniqueness: true

  attr_accessor :most_relevant_statistic

  delegate :win_rate, :pick_rate, :performance, to: :most_relevant_statistic

  def self.translatable_fields
    ChampionTranslation.column_names - %w[id locale champion_id created_at updated_at]
  end

  def translations
    champion_translations
  end

  include Translatable

  def self.all_champions
    Rails.cache.fetch("#{Time.zone.today.to_fs(:iso8601)}/all_champions", expires_in: 12.hours) do
      Champion.all
    end
  end

  def self.most_relevant_statistic_for(champion, tier:, region:, position:)
    Rails.cache.fetch("#{Time.zone.today.to_fs(:iso8601)}/#{champion.key}/#{tier}/#{region}/#{position}", expires_in: 12.hours) do
      champion.statistics.where(tier:, region:, position: position == 'all' ? Statistic.positions.keys : position).order(pick_rate: :desc).first
    end
  end

  def self.all_champions_filtered_by(tier:, region:, position:)
    Champion.all_champions.select do |champion|
      champion.most_relevant_statistic = Champion.most_relevant_statistic_for(champion, tier:, region:, position:)
      champion.most_relevant_statistic.present?
    end
  end

  def self.sort_champions_array_by(champions, field:, sort_type:)
    champions = champions.sort do |c1, c2|
      c1.send(field) <=> c2.send(field)
    end
    if sort_type.to_s == 'asc'
      champions
    else
      champions.reverse
    end
  end
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  # helper Statistic::available_positions # TODO

  def index
    field = params[:sort]&.split('-')&.first || 'name_id'
    sort_type = params[:sort]&.split('-')&.second || 'asc'
    @sort = { field => sort_type }

    br_msg = "Invalid sort #{field}: #{sort_type}"
    raise ActionController::BadRequest.new, br_msg unless field.in?(['name_id', 'performance', 'win_rate', 'pick_rate']) && sort_type.in?(['asc', 'desc'])

    @tier = params[:tier] || 'all'
    raise ActionController::BadRequest.new, "Invalid tier #{@tier}" unless Statistic.a_valid_tier? @tier

    @region = params[:region] || 'global'
    raise ActionController::BadRequest.new, "Invalid region #{@region}" unless Statistic.a_valid_region? @region

    @position = params[:position] || 'all'
    raise ActionController::BadRequest.new, "Invalid position #{@position}" unless Statistic.a_valid_position? @position

    all_champions = Champion.all_champions_filtered_by(tier: @tier, region: @region, position: @position)
    @champions = Champion.sort_champions_array_by(all_champions, field:, sort_type:)
  end

  def show
    @champion = Champion.find(params[:id])
  end
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/views/champions/_champion_table.html.erb
<% champions.each_with_index do |champion, idx| %>
    <tr id="champion-<%= idx + 1 %>" name="<%= champion.name_id %>">
        <th scope="row"><span class="small fw-lighter ms-2"><%= idx+1 %></span></th>
        <td>
            <a class="d-flex align-items-center text-decoration-none text-light" href="<%= champion_path(champion) %>">
                <%= image_tag "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/champion/#{champion.image_full}", class: 'mx-2 rounded-circle', size: 38 %>
                <%= champion.name %>
            </a>
        </th>
        <td class="font-monospace text-uppercase small"><%= translated_position champion.most_relevant_statistic.position %></td>
        <td>
            <div class="hstack gap-2">
                <span class="small" style="width: 3.5em;">
                    <%= number_to_percentage(champion.most_relevant_statistic.win_rate * 100.0, precision: 2) %>
                </span>
                <div class="vr"></div>
                <span class="badge bg-<%= winrate_badge_class_for(champion.most_relevant_statistic.win_rate) %>">
                    <%= winrate_badge_text_for(champion.most_relevant_statistic.win_rate) %>
                </span>
            </div>
        </td>
        <td>
            <div class="hstack gap-2">
                <span class="small" style="width: 3.5em;"><%= number_to_percentage(champion.most_relevant_statistic.pick_rate * 100.0, precision: 2) %></span>
                <div class="vr"></div>
                <span class="badge bg-<%= pickrate_badge_class_for(champion.most_relevant_statistic.pick_rate) %>">
                    <%= pickrate_badge_text_for(champion.most_relevant_statistic.pick_rate) %>
                </span>
            </div>
        </td>
    </tr>
<% end %>

app/views/champions/_filter_table_column.html.erb
<a href="#" class="text-decoration-none fw-<%= @sort[field] ? 'bolder' : 'bold' %> text-white" data-action="click->championssort#update_sort" value="<%= field %>" data-sort-triggered="<%= @sort[field].present? %>" data-sort-value="<%= @sort[field] || 'desc' %>">
    <%= t("champion.#{column_title}") %>
    <% if @sort[field] %>
        <i class="fa fa-solid fa-angle-<%= @sort[field] == 'asc' ? 'up' : 'down' %> fw-bold"></i>
    <% end %>
</a>

app/views/champions/_performance_badge.html.erb
<span class="badge bg-<%= performance_badge_class_for(statistic) %>"><%= performance_badge_text_for(statistic) %></span>

app/views/champions/index.html.erb
<div class="container-fluid px-0 bg-dark" style="background-image: url(<%= image_url 'Malzahar_0.jpg' %>);background-size: cover; background-repeat: no-repeat; background-attachment: fixed;">
    <div class="container-fluid shade-bg">
        <div class="container-sm">
        <table class="table table-striped table-dark my-0">
            <thead>
                <th scope="col"></th>
            <thead>
            <tbody>
                <td scope="col">
                    <div class="container-sm py-1">
                        <form id="filter-form" action="<%= champions_path %>" method="get">
                            <input type="hidden" name="region" id="form-region" value="<%= @region %>">
                            <input type="hidden" name="tier" id="form-tier" value="<%= @tier %>">
                            <input type="hidden" name="position" id="form-position" value="<%= @position %>">
                            <input type="hidden" name="sort" id="form-sort" value="<%= "#{@sort.keys.first.to_s}-#{@sort.values.first.to_s}" %>">
                        </form>
                        <div class="d-flex justify-content-around">
                            <div class="hstack gap-3">
                                <div class="col">
                                    <div class="dropdown">
                                        <button class="btn btn-sm btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            <span class="text-uppercase fw-bold"><%= translated_region @region %></span>
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-dark" data-controller="championsfilter">
                                            <% available_regions.each do |region| %>
                                                <li>
                                                    <a class="dropdown-item <%= 'active' if @region == region %>" href="#" data-action="click->championsfilter#update_filters" value="<%= region %>" input-target="form-region">
                                                        <span class="text-uppercase small"><%= translated_region region %></span>
                                                    </a>
                                                </li>
                                            <% end %>
                                        </ul>
                                    </div>
                                </div>
                                <div class="vr"></div>
                                <div class="col">
                                    <div class="dropdown">
                                        <button class="btn btn-sm btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            <span class="text-uppercase fw-bold"><%= translated_tier @tier %></span>
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-dark" data-controller="championsfilter">
                                            <% available_tiers.each do |tier| %>
                                                <li>
                                                    <a class="dropdown-item <%= 'active' if @tier == tier %>" href="#" data-action="click->championsfilter#update_filters" value="<%= tier %>" input-target="form-tier">
                                                        <span class="text-uppercase small"><%= translated_tier tier %></span>
                                                    </a>
                                                </li>
                                            <% end %>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="btn-group" role="group" aria-label="roles" data-controller="championsfilter">
                                <% available_positions.each do |position| %>
                                    <button class="btn btn-sm <%= @position == position ? 'btn-secondary' : 'btn-outline-secondary' %>" data-action="click->championsfilter#update_filters" value="<%= position %>" input-target="form-position">
                                        <span class="text-uppercase fw-bold"><%= translated_position position %></span>
                                    </button>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </td>
            </tbody>
        </table>
        </div>
        <div class="container-sm">
            <table class="table table-striped table-dark table-hover">
                <thead data-controller="championssort">
                    <th scope="col"><span class="small fw-lighter ms-2">#</span></th>
                    <th scope="col text-capitalize">
                        <%= render 'champions/filter_table_column', field: 'name_id', column_title: 'champion' %>
                    </th>
                    <th scope="col text-capitalize">
                        <%= t('champion.position')%>
                    </th>
                    <th scope="col text-capitalize">
                        <%= render 'champions/filter_table_column', field: 'win_rate', column_title: 'win_rate' %>
                    </th>
                    <th scope="col text-capitalize">
                        <%= render 'champions/filter_table_column', field: 'pick_rate', column_title: 'pick_rate' %>
                    </th>
                </thead>
                <tbody class="align-middle">
                    <%= render('champions/champion_table', champions: @champions, tier: @tier, region: @region, position: @position, primary_role: 'all') %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/champions/show.html.erb
<div class="container-sm bg-dark px-0">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="<%= "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/#{@champion.name}_0.jpg" %>" class="d-block w-100 top-gradient" alt="...">
        <div class="container-fluid top-gradient"></div>
      </div>
      <div class="carousel-item">
        <img src="<%= "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/#{@champion.name}_1.jpg" %>" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="<%= "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/#{@champion.name}_2.jpg" %>" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="px-3">
    <h1 class="display-4 my-2"><%= @champion.name %></h1>
    <section>
      <p class="small fw-light">
        <%= @champion.lore %>
      </p>
    </section>
  </div>
</div>